project:
  type: website
  output-dir: docs

website:
  title: "asark | STA 9750"
  description: "STA 9750 Course Projects - Baruch College"
  site-url: "https://asark00.github.io/STA9750-2026-SPRING/"
  navbar:
    search: false

format:
  html:
    theme: none
    toc: false
    page-layout: full

editor:
  mode: source